name: 'simple_transformer_pytorch'

model:
  _target_: src.models.trafo_predictor.TransformerPredictor_Pytorch
  input_dim: 10
  model_dim: 32
  num_heads: 4
  num_classes: 10
  num_layers: 3
  dropout: 0.0

inference:
  ckpt_path: ''
  test_seq: [1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 0, 1, 2, 3, 4, 5, 6]


