name: "diffusion_policy"

pl_module:
  _target_: src.pl_modules.diffusion_policy.DiffusionTransformerHybridImagePolicy
  num_stack: 10
  causal_attn: true
  crop_shape:
  - 84
  - 84
  eval_fixed_crop: true
  t_p: 20
  n_action_steps: 8
  n_cond_layers: 0
  n_emb: 256
  n_head: 4
  n_layer: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_cond: true
  obs_encoder_group_norm: true
  p_drop_attn: 0.3
  p_drop_emb: 0.0
  shape_meta:
    action:
      shape:
      - 6
    obs:
      agent_pos:
        shape:
        - 2
        type: low_dim
      image:
        shape:
        - 3
        - 96
        - 96
        type: rgb
  time_as_cond: true
  train_tasks: bind+order+recover+imitation
  mask_type: latent_mask
  weight:
    cr_m_nce_loss: 1.0
    masked_fom_loss: 1.0
    mask_fusion_nce_loss: 1.0
    mask_cr_t_nce_loss: 1.0
    recover_loss: 1.0
    fom_loss: 1.0