name: "diffusion_policy"

pl_module:
  _target_: src.pl_modules.diffusion_policy.DiffusionPolicyFramework
  time_as_cond: true
  action: "real_delta_target"
  train_tasks: bind+order+recover+imitation
  mask_type: latent_mask
  ema:
    _target_: src.models.utils.helpers.EMAModel
    inv_gamma: 1.0
    max_value: 0.999
    min_value: 0.0
    power: 0.75
    update_after_step: 0
  weight:
    cr_m_nce_loss: 1.0
    masked_fom_loss: 1.0
    mask_fusion_nce_loss: 1.0
    mask_cr_t_nce_loss: 1.0
    recover_loss: 1.0
    fom_loss: 1.0