name: "ltmask_bind_fom_rec_imi"
pl_module:
  _target_: src.pl_modules.ssl_nce_framework.TransformerPredictorPl
  num_stack: 5
  train_tasks: bind+order+recover+imitation
  masked_train: latent_mask
  weight:
    cr_m_nce_loss: 1.0
    masked_fom_loss: 1.0
    mask_fusion_nce_loss: 1.0
    mask_cr_t_nce_loss: 1.0
    recover_loss: 1.0
    fom_loss: 1.0

  ema:
    _target_: src.models.utils.helpers.EMAModel
    inv_gamma: 1.0
    max_value: 0.9999
    min_value: 0.0
    power: 1.0
    update_after_step: 0