name: "mask_bind_fom_ctnce_imi"
pl_module:
  _target_: src.pl_modules.ssl_nce_framework.TransformerPredictorPl
  num_stack: 5
  train_tasks: bind+order+cross_time_nce+imitation
  masked_train: True
  weight:
    cr_m_nce_loss: 1.0
    masked_fom_loss: 1.0
    mask_fusion_nce_loss: 1.0
    mask_cr_t_nce_loss: 1.0
    recover_loss: 1.0
    fom_loss: 1.0
