name: nomask_bind_imi
pl_module:
  _target_: src.pl_modules.ssl_nce_framework.TransformerPredictorPl
  num_stack: 5
  train_tasks: bind+imitation
  masked_train: False
  weight:
    cr_m_nce_loss: 2.0

