name: 'EarlySum_vit_nores'

model:
  _target_: src.models.ss_nce_framework.VisionAudioFusion_EarlySum
  model_dim: 256
  preprocess_audio_args:
    _target_: src.models.utils.mel_spec.MelSpec
    length: 40000
    sr: 16000
    n_mels: 64
    norm_audio: false
    hop_ratio: 0.051
  tokenization_audio:
    _target_: src.models.utils.tokenization.Vanilla2dTokenization
    channel_size: 1
    patch_size: [64, 10]
    input_size: [64, 51]
    model_dim: ${models.model.model_dim}
  pe_audio:
    _target_: src.models.encoders.identity.get_identity_encoder
  encoder_audio_args:
    _target_: src.models.encoders.identity.get_identity_encoder


  preprocess_vision_args:
    _target_: src.models.encoders.identity.get_identity_encoder
  tokenization_vision:
    _target_: src.models.vit_implementations.Vit
    channel_size: 3
    model_dim: ${models.model.model_dim}
    num_heads: 8
    num_layers: 4
    patch_size: [8, 8]
    input_size: [67, 90]
    num_emb: 100
  pe_vision:
    _target_: src.models.encoders.identity.get_identity_encoder
  encoder_vision_args:
    _target_: src.models.encoders.identity.get_identity_encoder
    

  preprocess_tactile_args:
    _target_: src.models.encoders.identity.get_identity_encoder
  tokenization_tactile:
    _target_: src.models.vit_implementations.Vit
    channel_size: 3
    model_dim: ${models.model.model_dim}
    num_heads: 8
    num_layers: 4
    patch_size: [6, 6]
    input_size: [54, 72]
    num_emb: 109  # 1 more aggregation token
  pe_tactile:
    _target_: src.models.encoders.identity.get_identity_encoder
  encoder_tactile_args:
    _target_: src.models.encoders.identity.get_identity_encoder


  pos_emb_args:
    _target_: src.models.utils.positional_encoding.StandardPositionalEncoding
    d_model: ${models.model.model_dim}


  transformer_classifier_args:
    _target_: src.models.vit_implementations.Transformer_Classifier_NoTokenNoEmb
    model_dim: ${models.model.model_dim}
    num_classes: 10
    num_heads: 8
    dropout: 0.0
    input_dropout: 0.0
    num_layers: 4
    add_positional_encoding: False



inference:
  ckpt_path: ' '

