# config_ssl_nce_framework.yaml


defaults:
- datasets: see_hear_feel
- models: aloha/vae
- optimizers: adam_steplr
- pl_modules: aloha/aloha
- trainers: aloha
- _self_


# General settings
task_name: "ss_nce"
variable_name: trainers.launch_trainer.repeat_trial
output_name: debug
seed: 42
results_dir: 'results'
data_folder_path: '/fs/scratch/rng_cr_bcai_dl_students/jin4rng/data'

hydra:
  sweeper:
    params:
      trainers.launch_trainer.repeat_trial: 1
      trainers.launch_trainer.max_epochs: 2
#      trainers.launch_trainer.monitor: "val_loss"
      datasets.dataloader.data_folder: ${data_folder_path}
      datasets.dataloader.args.num_stack: 10
      datasets.dataloader.args.len_lb: 10
      models.model.action_decoder.num_queries: 10
      models.model.obs_encoder.model_dim: 512
      optimizers: adam_steplr
      datasets.dataloader.batch_size: 16
      pl_modules.pl_module.num_stack: ${datasets.dataloader.args.num_stack}
#      models.model.transformer_classifier_args._target_: src.models.vit_implementations.Vit_ClassifierVanillaNoPatch

  sweep:  # didn't use ${hydra.runtime.choices.pl_modules} because "/"
    dir: ./${results_dir}/${task_name}/${datasets.name}/${output_name}_${now:%m-%d-%H:%M:%S}/${pl_modules.name}_${models.name}_${optimizers.name}/
    # only controls where config.yaml is saved
    subdir: ./
  run: # control where multirun.yaml is saved
    dir: ${hydra.sweep.sub}/.hydra



