# config_progress_prediction.yaml


defaults:
- datasets: bautiro_drilling
- models: short_drilling_progress/ultrasonic_bind_vanilla
- optimizers: adam_steplr
- pl_modules: ultrasonic_bind
- trainers: short_drilling_progress_prediction
- _self_


# General settings
task_name: "short_term_drilling_progress_prediction"
variable_name: datasets.dataloader.step_size&datasets.dataloader.train_batch_size
output_name: stepsize_bs_epo15
seed: 42
results_dir: 'results'
data_folder_path: '/fs/scratch/rng_cr_bcai_dl_students/jin4rng/data/'
# output dir path: smart_sensor_fusion/results/task name/dataset name/model name/time stamp/

hydra:
  verbose: False
  sweeper:
    params:
      trainers.launch_trainer.max_epochs: 15
      datasets.dataloader.data_folder: ${data_folder_path}
      datasets.dataloader.z_norm: True
#      models.model.model_dim: 256
      datasets.dataloader.train_batch_size: 32,64,128,256
      datasets.dataloader.step_size: 50000,75000,100000,125000
      datasets.dataloader.val_batch_size: 32
  sweep:
    # control where output saved
#    dir: ./${results_dir}/${task_name}/${datasets.name}/${models.name}${optimizers.name}/${variable_name}/${${variable_name}}_${now:%m-%d-%H:%M:%S}
    dir: ./${results_dir}/${task_name}/${datasets.name}/${models.name}${optimizers.name}/${output_name}_${now:%m-%d-%H:%M:%S}
    # only controls where config.yaml is saved
    subdir: ./
  run: # control where multirun.yaml is saved
    dir: ${hydra.sweep.dir}/.hydra



