datasets:
  name: dummy
  dataloader:
    _target_: src.datasets.dummy_robot_arm.get_loaders
    batch_size: 8
    data_folder: /fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/jin4rng/data/cuponplate1_robot_demos/
    drop_last: true
    debug: true
    args:
      ablation: vf
      num_stack: 10
      frameskip: 5
      no_crop: true
      crop_percent: 0.0
      resized_height_v: 480
      resized_width_v: 640
      len_lb: 10
      p_mean: 0
      p_std: 0
      o_mean: 0
      o_std: 0
      sampling_time: 100
      source: true
      norm_type: limit
      smooth_factor:
      - 1.0e-05
      - 1.0e-05
      - 1.0e-05
      - 1.0e-05
      - 1.0e-05
      - 1.0e-05
      catg: resample
models:
  name: vae_vanilla
  model:
    _target_: src.models.aloha_vanilla.build
    replace_args:
      camera_names:
      - vf
      num_queries: 10
      state_dim: 7
      hidden_dim: 512
      output_layer_index: -1
  inference:
    ckpt_path: ' '
optimizers:
  name: coswarmup
  optimizer:
    _target_: torch.optim.Adam
    lr: 4.0e-05
    weight_decay: 0.0001
  scheduler:
    _target_: diffusers.optimization.get_cosine_schedule_with_warmup
    num_training_steps: 20200
    num_warmup_steps: 2020
pl_modules:
  name: aloha
  pl_module:
    _target_: src.pl_modules.aloha.AlohaPolicy
    action: position
    train_tasks: bind+order+recover+imitation
    mask_type: latent_mask
    weight:
      cr_m_nce_loss: 1.0
      masked_fom_loss: 1.0
      mask_fusion_nce_loss: 1.0
      mask_cr_t_nce_loss: 1.0
      recover_loss: 1.0
      fom_loss: 1.0
      kl_divergence: 10
trainers:
  launch_trainer:
    repeat_trial: 1
    max_epochs: 200
    monitor: val_vae_loss
    mode: min
    save_top_k: 1
task_name: dummy_aloha
variable_name: pl_modules.name___models.name___pl_modules.pl_module.action___optimizers.name___optimizers.optimizer.lr___optimizers.optimizer.weight_decay___pl_modules.pl_module.weight.kl_divergence___datasets.dataloader.args.source___datasets.dataloader.args.resized_height_v___datasets.dataloader.args.resized_width_v
output_name: dummy_aloha_vanilla_cuponplate
seed: 42
results_dir: /home/jin4rng/Documents/code/smart_sensor_fusion/results/
data_folder_path: /fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/jin4rng/data/cuponplate1_robot_demos/
