name: 'dummy'

dataloader:
  # norm_audio: True
  _target_: src.datasets.vision_audio_robot_arm.get_loaders
  batch_size: 128
  data_folder: ''
  drop_last: True
  debug: False
  args:
    ablation: 'vf_ah'
    num_stack: 5
    frameskip: 5
    no_crop: True
    crop_percent: 0.0
    resized_height_v: 240
    resized_width_v: 320
    len_lb: 10
    p_mean: 0
    p_std: 0
    o_mean: 0
    o_std: 0
    sampling_time: 100
    source: True
    norm_type: "limit"
    smooth_factor:
      - 1e-5
      - 1e-5
      - 1e-5
      - 1e-5
      - 1e-5
      - 1e-5
    catg: resample